### PR TITLE
Feature hierarchy

### PR DESCRIPTION
**Pull request by rociac**
Looking forward to your feedback on our project. Thanks in advance for the review.

### CODE REVIEW

**Comment by samgaco** [comment]
Hi guys :hand: 

A good project so far :100: , you've outlined the structure really well and it feels like the original, the readme file is well documented and the code looks clean :+1:  . 
**Here are some points that you should improve before proceeding;**

* **The navigation bar** should be enclosed within `<nav>` tags, and inside you should have 7 different containers.  (the logo, articles, books, events, etc.) ( `<div>` is recommended for the containers). The containers should be positioned with floats or display flex.

* The containers under the search bar and the containers in the section "person of the week" and on, should have an embedded image (it doesn't matter which image) at the top left corner, with the title of the article under it.
article

sec2

* **Bear in mind the following semantic structure**; All content should be wrapped within` <main>` tags (you only have a small portion of the content currently inside the `<main>` tags), every child of main should be enclosed within a `<section>` tag and every child of section within an `<article>` tag.

* **Footer**:  The links in the footer should be centered. You can use either floats or display flex. The elements should be an unorganized list `<ul>`. The links in the footer should be list items` <li>` positioned with either floats or display flex. The footer should preserve the structure of the original.

footer

Please :pray: , **work on these changes and submit again for a code review** :muscle: . Regards!.

**Comment by KaushikShivam** [comment]
Hello. We have made the necessary changes. Sending the review request again.

**Comment by Oghenebrume50** [comment]
Hi team great job so far, I see that you made the correct changes as the previous reviewer stated. There is just one thing left, you have to make it responsive, minimize the actual page gradually you will see how the elements change position please make yours similar. This is required. Please do this and submit for re-review.

**Comment by Oghenebrume50** [comment]
Hi, @KaushikShivam 
I've realized that in this project the responsiveness is not required, my bad man.
I am sorry to mislead you, haven't done that on purpose :blush:
As it was the only thing I spotted, it means that everything else is good ✅ 
Feel free to merge it 👍

**Comment by KaushikShivam** [comment]
No worries, man! You took out time to review our code and guide us which is great regardless of the mistake. Thank you.
Also, I have a question. Do we have to merge it and submit again for review? or Will it be updated automatically?

**Pull request merged**
